export const paths = {
  login: '/login',
  verificar: '/verificar',
  crearPassword: '/crear-password',
  aceptarInvitacion: '/aceptar-invitacion',
  revision: '/revision',
  driverDetail: (id: string | number) => `/revision/${id}`,
  vehiculos: '/vehiculos',
  vehicleDetail: (id: string | number) => `/vehiculos/${id}`,
  conductores: '/conductores',
  reportes: '/reportes',
  reporteDetail: (rol: string, id: string | number) => `/reportes/${rol}/${id}`,
  zonas: '/zonas',
  administradores: '/administradores',
  ajustes: '/ajustes',
} as const
